# Dataset Path

path: ../../../face_mask_dataset6 # relative to this file

train: train/images # relative to path
train_labels: train/labels # relative to path
val: valid/images # relative to path
val_labels: valid/labels # relative to path
test: test/images # relative to path
test_labels: test/labels # relative to path

names:
  0: incorrect_mask
  1: with_mask
  2: without_mask 
